services:

  strongswan-base:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      args:
        BUILD_QKD_ETSI: "true"
        BUILD_QKD_KEM: "true"
        QKD_BACKEND: ${QKD_BACKEND:-simulated}
        ACCOUNT_ID: ${ACCOUNT_ID:-}
        ETSI_API_VERSION: ${ETSI_API_VERSION:-014}
    image: strongswan-base:latest
    container_name: strongswan-base
    pull_policy: never
      
  bob:
    image: strongswan-base:latest
    container_name: bob
    pull_policy: never
    depends_on:
      - strongswan-base
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_MODULE
    stdin_open: true
    tty: true
    environment:
      - ETSI_API_VERSION=${ETSI_API_VERSION:-014}
    volumes:
      - ./bob:/etc/swanctl
      - ./config/shared:/etc/swanctl/shared
      - ./strongswan.conf:/etc/strongswan.conf
      - ./results:/output
      - ./qkd_certs:/qkd_certs
    networks:
      internet:
        ipv4_address: 172.30.0.2
      intranet:
        ipv4_address: 172.31.0.2
        
  alice:
    image: strongswan-base:latest
    container_name: alice
    pull_policy: never
    depends_on:
      - strongswan-base
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_MODULE
    stdin_open: true
    tty: true
    environment:
      - ETSI_API_VERSION=${ETSI_API_VERSION:-014}
    volumes:
      - ./alice:/etc/swanctl
      - ./config/shared:/etc/swanctl/shared
      - ./strongswan.conf:/etc/strongswan.conf
      - ./benchmark_utils:/etc/swanctl/benchmark_utils
      - ./results:/output
      - ./qkd_certs:/qkd_certs
    networks:
      internet:
        ipv4_address: 172.30.0.3

  # QKD Servers
  qkd_server_alice:
    build:
      context: ./etsi-qkd-004/server
    container_name: qkd_server_alice
    pull_policy: never
    environment:
      - SERVER_CERT_PEM=/certs/server_cert_qkd_server_alice.pem
      - SERVER_CERT_KEY=/certs/server_key_qkd_server_alice.pem
      - CLIENT_CERT_PEM=/certs/client_cert_qkd_server_alice.pem
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=25575
      - BUFFER_PATH=/dev/shm/qkd_buffer
      - BUFFER_SIZE=1000000
      - QOS_KEY_CHUNK_SIZE=32
      - QOS_MAX_BPS=40000
      - QOS_MIN_BPS=5000
      - QOS_JITTER=10
      - QOS_PRIORITY=0
      - QOS_TIMEOUT=5000
      - QOS_TTL=3600
    volumes:
      - ./qkd_certs/etsi004:/certs
      - qkd_shared_alice:/dev/shm
    ports:
      - "25575:25575"
    networks:
      internet:
        ipv4_address: 172.30.0.10

  qkd_server_bob:
    build:
      context: ./etsi-qkd-004/server
    container_name: qkd_server_bob
    pull_policy: never
    environment:
      - SERVER_CERT_PEM=/certs/server_cert_qkd_server_bob.pem
      - SERVER_CERT_KEY=/certs/server_key_qkd_server_bob.pem
      - CLIENT_CERT_PEM=/certs/client_cert_qkd_server_bob.pem
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=25576
      - BUFFER_PATH=/dev/shm/qkd_buffer
      - BUFFER_SIZE=1000000
      - QOS_KEY_CHUNK_SIZE=32
      - QOS_MAX_BPS=40000
      - QOS_MIN_BPS=5000
      - QOS_JITTER=10
      - QOS_PRIORITY=0
      - QOS_TIMEOUT=5000
      - QOS_TTL=3600
    volumes:
      - ./qkd_certs/etsi004:/certs
      - qkd_shared_bob:/dev/shm
    ports:
      - "25576:25576"
    networks:
      internet:
        ipv4_address: 172.30.0.11

  generate_key_alice:
    build:
      context: ./etsi-qkd-004/keys
    container_name: generate_key_alice
    pull_policy: never
    environment:
      - BUFFER_SIZE=1000000
      - BUFFER_PATH=/dev/shm/qkd_buffer
      - MODE=sender
      - HOST=generate_key_bob
      - PORT=5000
      - SKR=12500
    volumes:
      - qkd_shared_alice:/dev/shm
    networks:
      internet:
        ipv4_address: 172.30.0.12

  generate_key_bob:
    build:
      context: ./etsi-qkd-004/keys
    container_name: generate_key_bob
    pull_policy: never
    environment:
      - BUFFER_SIZE=1000000
      - BUFFER_PATH=/dev/shm/qkd_buffer
      - MODE=receiver
      - PORT=5000
      - SKR=12500
    volumes:
      - qkd_shared_bob:/dev/shm
    ports:
      - "5000:5000"
    networks:
      internet:
        ipv4_address: 172.30.0.13

networks:
  internet:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
  intranet:
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/16

volumes:
  qkd_shared_alice:
    driver_opts:
      type: tmpfs
      device: tmpfs
  qkd_shared_bob:
    driver_opts:
      type: tmpfs
      device: tmpfs