# QKD-IPSec Benchmark Configuration

# Docker environment configuration
docker:
  build:
    strongswan_version: "6.0.0beta6"
    build_qkd_etsi: true
    build_qkd_kem: true
    build: true
    use_cache: false

  # QKD backend configuration
  qkd:
    etsi_api_version: "004"  # Options: "004", "014"
    backend: "python_client"  # Options: "simulated", "qukaydee", "cerberis-xgr", "python_client"
    account_id: "2509"  # Required for QuKayDee only
    initiation_mode: "client"  # Options: "client", "server"

  # Docker Compose files for different modes
  compose_files:
    single_machine: "docker-compose.004.yml"
    distributed: "docker-compose.004.distr.yml"

  network:
    mode: "single-machine"  # Options: "single-machine", "distributed"
    alice:
      local_ip: "auto"     # Auto-detect or specify
      container_ip: "172.30.0.3"
      qkd_server_port: 25575
    bob:
      local_ip: "auto"     # Auto-detect or specify  
      container_ip: "172.30.0.2"
      qkd_server_port: 25576
    coordination_port: 8080

# Test parameters
test:
  # Default network conditions
  network:
    apply: true
    latency: 0             # Milliseconds
    jitter: 0              # Milliseconds
    packet_loss: 10        # Percentage
    duration: "180m"       # Duration string

  # Test iterations
  iterations: 5

  # Analysis options
  analyze_results: true
  log_scale: false       # Use logarithmic scale for charts

# Proposal configuration
proposals:
  file: "config/shared/proposals_config.yml"